services:
  - type: web
    name: erasmus-talk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn start:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DB_CONNECTION_STR
        sync: false  # You'll need to set this in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true